### ISSUE TITLE
NullPointer Exception when running PipelinePreprocessing

### ISSUE THREAD

**Issue by blodstone** [UKPLab/emnlp2017-cmapsum-corpus#1]
I have put the correct data and englishRNN.ser in its place but when I try to run PipelinePreprocessing, it gave me this error:

```
Sep 27, 2017 10:12:40 AM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase scan(393)
INFO: Scanning [file:/home/acp16hh/Projects/Research/Exp_7_Improve_CMap/src/baseline/emnlp2017-cmapsum-corpus/baseline/data/CMapSummaries/train/]
Sep 27, 2017 10:12:40 AM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase initialize(224)
INFO: Found [578] resources to be read
Sep 27, 2017 10:12:41 AM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
INFO: :: loading settings :: url = jar:file:/home/acp16hh/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Sep 27, 2017 10:12:41 AM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
INFO: :: loading settings :: url = jar:file:/home/acp16hh/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Sep 27, 2017 10:12:41 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFO: Producing resource from [jar:file:/home/acp16hh/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-tagger-en-bidirectional-distsim/jars/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-upstream-tagger-en-bidirectional-distsim-20140616.jar!/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/tagger-en-bidirectional-distsim.tagger] redirected from [jar:file:/home/acp16hh/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim/jars/de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim-20140616.1.jar!/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/tagger-en-bidirectional-distsim.properties]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sep 27, 2017 10:12:43 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFO: Producing resource took 1399ms
Sep 27, 2017 10:12:43 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFO: Producing resource from jar:file:/home/acp16hh/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.8.0/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.8.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-ptb-pos.map
Sep 27, 2017 10:12:43 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFO: Producing resource took 0ms
Sep 27, 2017 10:12:44 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFO: Producing resource from file:/home/acp16hh/Projects/Research/Exp_7_Improve_CMap/src/baseline/emnlp2017-cmapsum-corpus/baseline/lib/englishRNN.ser
Sep 27, 2017 10:12:44 AM de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser$StanfordParserModelProvider produceResource(538)
INFO: Loading parser from serialized file file:/home/acp16hh/Projects/Research/Exp_7_Improve_CMap/src/baseline/emnlp2017-cmapsum-corpus/baseline/lib/englishRNN.ser ...
Sep 27, 2017 10:12:46 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFO: Producing resource took 1211ms
Sep 27, 2017 10:12:46 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFO: Producing resource from [jar:file:/home/acp16hh/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.8.0/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.8.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-ptb-pos.map] redirected from [jar:file:/home/acp16hh/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.8.0/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.8.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-default-pos.map]
Sep 27, 2017 10:12:46 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFO: Producing resource took 1ms
Sep 27, 2017 10:12:46 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFO: Producing resource from [jar:file:/home/acp16hh/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl/1.8.0/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl-1.8.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/syntax/tagset/en-ptb-constituency.map] redirected from [jar:file:/home/acp16hh/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl/1.8.0/de.tudarmstadt.ukp.dkpro.core.api.syntax-asl-1.8.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/syntax/tagset/en-default-constituency.map]
Sep 27, 2017 10:12:46 AM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFO: Producing resource took 1ms
Sep 27, 2017 10:12:47 AM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(417)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:411)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at preprocessing.PipelinePreprocessing.main(PipelinePreprocessing.java:74)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.parser.dvparser.DVModel.getVocabWord(DVModel.java:688)
	at edu.stanford.nlp.parser.dvparser.DVModel.getWordVector(DVModel.java:678)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:106)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.score(DVParserCostAndGradient.java:82)
	at edu.stanford.nlp.parser.dvparser.DVModelReranker$Query.score(DVModelReranker.java:62)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.rerank(RerankingParserQuery.java:93)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.parse(RerankingParserQuery.java:67)
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:407)
	... 10 more

Sep 27, 2017 10:12:47 AM org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl processAndOutputNewCASes(273)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:411)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at preprocessing.PipelinePreprocessing.main(PipelinePreprocessing.java:74)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.parser.dvparser.DVModel.getVocabWord(DVModel.java:688)
	at edu.stanford.nlp.parser.dvparser.DVModel.getWordVector(DVModel.java:678)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:106)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.score(DVParserCostAndGradient.java:82)
	at edu.stanford.nlp.parser.dvparser.DVModelReranker$Query.score(DVModelReranker.java:62)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.rerank(RerankingParserQuery.java:93)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.parse(RerankingParserQuery.java:67)
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:407)
	... 10 more

Exception in thread "main" org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:411)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:150)
	at preprocessing.PipelinePreprocessing.main(PipelinePreprocessing.java:74)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.parser.dvparser.DVModel.getVocabWord(DVModel.java:688)
	at edu.stanford.nlp.parser.dvparser.DVModel.getWordVector(DVModel.java:678)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:106)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.forwardPropagateTree(DVParserCostAndGradient.java:113)
	at edu.stanford.nlp.parser.dvparser.DVParserCostAndGradient.score(DVParserCostAndGradient.java:82)
	at edu.stanford.nlp.parser.dvparser.DVModelReranker$Query.score(DVModelReranker.java:62)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.rerank(RerankingParserQuery.java:93)
	at edu.stanford.nlp.parser.lexparser.RerankingParserQuery.parse(RerankingParserQuery.java:67)
	at de.tudarmstadt.ukp.dkpro.core.stanfordnlp.StanfordParser.process(StanfordParser.java:407)
	... 10 more

```
Did I miss something? Thank you

**Comment by blodstone** [comment]
Nevermind, I found out that I used the wrong version of englishRNN.ser. Fixed it already.
